### ISSUE TITLE
Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by oberruti** [arthurgeron/eslint-plugin-react-usememo#26]
Seeing this in a lot of cases

TypeError: Cannot read properties of undefined (reading '1')
    Occurred while linting `/fullPrivatePathHere.tsx:38`
    Rule: "@arthurgeron/react-usememo/require-usememo"
    
    
    -------
    
    Dependency added as `dev dependency` -> `"@arthurgeron/eslint-plugin-react-usememo": "^2.1.3",`
    
    Configured like this:
    ```
     '@arthurgeron/react-usememo/require-usememo': [
      'warn',
      {
        strict: true,
        checkHookReturnObject: true,
        fix: { addImports: true },
        checkHookCalls: true,
        ignoredHookCallsNames: {},
      },
    ],
    ```

**Comment by arthurgeron-work** [comment]
Can you try removing "ignoredHookCallsNames"? It was meant to be defined only when it has parameters. I'll review the parameters later and add safety checks. Thank you for the feedback!

**Comment by oberruti** [comment]
@arthurgeron-work thank you, will try and let you know

**Comment by oberruti** [comment]
@arthurgeron-work I still have the same issue without that command
it looks like this now:

```
'@arthurgeron/react-usememo/require-usememo': [
      'warn',
      {
        strict: true,
        checkHookReturnObject: true,
        fix: { addImports: true },
        checkHookCalls: true,
      },
    ],
```

**Comment by arthurgeron-work** [comment]
I'm not able to reproduce it locally, could you provide the code for the file that causes this exception? It doesn't have to be exactly the same, as long as it causes the error.
<img width="929" alt="Captura de Tela 2023-11-21 às 22 28 37" src="https://github.com/arthurgeron/eslint-plugin-react-usememo/assets/71399856/9e34b2c8-b26e-4297-ac3f-714b23a4a6e4">

**Comment by oberruti** [comment]
@arthurgeron-work for example:

```
[Error - 19:38:21] An unexpected error occurred:
[Error - 19:38:21] TypeError: Cannot read properties of undefined (reading '1')
Occurred while linting /fullPath/index.tsx:298
Rule: "@arthurgeron/react-usememo/require-usememo"
    at Object.insertTextAfterRange
    at Object.insertTextAfter
    at addReactImports 
    at fixBasedOnMessageId
    at Object.fix
    at normalizeFixes
    at fileWithPath.js:365:49
    at Object.report
    at report 
    at checkForErrors
```

the code just says:

```
renderCell: (user) => <RoleIndicator roles={['role']} user={user} />,
```

**Comment by arthurgeron-work** [comment]
I'd need the entire code for that component/hook, or something similar; That line of code itself isn't enough for me to reproduce it locally. 
Also if the error gives you any stack track please post it here as well.

**Comment by arthurgeron-work** [comment]
Please check if the issue is fixed in this beta version: `@arthurgeron/eslint-plugin-react-usememo@2.1.3--beta0`

> the code just says:
> 
> ```
> renderCell: (user) => <RoleIndicator roles={['role']} user={user} />,
> ```


That line of code itself isn't enough for me to reproduce it locally, if you could please provide a full example. 
It seems like the problem is happening during eslint --fix, is that right?

**Comment by oberruti** [comment]
> That line of code itself isn't enough for me to reproduce it locally, if you could please provide a full example.
> It seems like the problem is happening during eslint --fix, is that right?

Unfortunately, it doesn't work either...
I'm asking for approval to share more code, will do as soon as I get an answer

**Comment by arthurgeron-work** [comment]
Did you have empty import statements? I think I might've been able to replicate the issue locally, please test this beta `@arthurgeron/eslint-plugin-react-usememo@2.1.4--beta0`, thanks!

**Comment by oberruti** [comment]
> Did you have empty import statements? I think I might've been able to replicate the issue locally, please test this beta `@arthurgeron/eslint-plugin-react-usememo@2.1.4--beta0`, thanks!

I don't!
Also I tried with this config:

```
 {
        strict: false,
        checkHookReturnObject: true,
        checkHookCalls: true,
      },
```

and doesn't work either, `@2.1.4--beta0` either :(

**Comment by arthurgeron** [comment]
It 

> @arthurgeron-work Some news!
> 
> ```
> {
>         strict: true,
>         checkHookReturnObject: true,
>         fix: { addImports: false },
>         checkHookCalls: true,
>       },
> ```
> 
> if I configure it like this, it works

It seems disabling addImports fixes your issue, the fix code is unable to handle something in your import statements. Do you mind sharing your complete `"react"` import statement?

**Comment by oberruti** [comment]
```
import type { ComponentProps, InputHTMLAttributes } from 'react'
import React from 'react'
import styled from '@emotion/styled'
import type { FieldPath, FieldValues } from 'react-hook-form'
import { useController } from 'react-hook-form'
import set from 'lodash/set'
```

**Comment by arthurgeron-work** [comment]
Thank you, this helps a lot. I'm sure it is getting confused because of `import type`, which is something I hadn't predicted when creating the auto fix logic. Once  I'll let you know once I've another beta version.

**Comment by oberruti** [comment]
> Thank you, this helps a lot. I'm sure it is getting confused because of `import type`, which is something I hadn't predicted when creating the auto fix logic. Once I'll let you know once I've another beta version.

Thank **YOU**

**Comment by arthurgeron** [comment]
I've released the version `2.1.4--beta1`, please see if it works now.

**Comment by arthurgeron** [comment]
Apparently, it didn't know where to place new imports on statements like `import React from 'react'`.

**Comment by oberruti** [comment]
@arthurgeron still continue seeing the same issue 👎  :
do you have covered:

```
import { useEffect } from 'react'
```

```
import React from 'react'
```

??

**Comment by arthurgeron-work** [comment]
> @arthurgeron still continue seeing the same issue 👎 : do you have covered:
> 
> ```
> import { useEffect } from 'react'
> ```
> 
> ```
> import React from 'react'
> ```
> 
> ??

Yes, there are cases like that in the test. Without a detailed stack-trace or the code for the file itself there's not much I can do to keep trying.

**Comment by arthurgeron-work** [comment]
Feel free to privately send me the file, I'm fine with signing NDAs as long as we get to the bottom of this bug :)

**Comment by oberruti** [comment]
@arthurgeron-work @arthurgeron  unfortunately by the moment I can't send anything, we are working with the team on preparing something to send you. Thank you!
From other side I wanted to ask if there is a way to add an option to apply these changes and checks (i.e. adding the `useMemo or useCallback` to a certain hooks, for example, in our case would be helpful to use this `eslint` rule to just check if the `config` object in the `useSubscription` is memorized, is that even possible? I was thinking in something like the option: `ignoredHookCallsNames: {},` but for checked hooks, for example: `validatedHookCallsNames: { useSubscription: true },`
Thank you!

**Comment by arthurgeron-work** [comment]
I appreciate the effort!🚀

As for validating only specific properties, it isn't possible currently. But I have plans for v3 where I'll bring greater flexibility and filtering capabilities.
About only running for a specific hook/file, you could add a override in your eslint config, leaving  `checkHookReturnObject` false as the default value, and as true for your useSubscription eslint override.

There's a difference between ignores, checks inside hooks are done on return statements, the "hook calls" wording mean checks that are ran against usages of the hook, e.g., in `const x = useSomething({y})` it'd verify if `y` is a primitive or memorized, so that's where  `ignoredHookCallsNames` acts. For checking memo rules **inside** hooks there's only the option to enable/disable it entirely, hence my suggestion about using eslint overrides.
 
By the way, for hook calls in your case you could use "ignoredHookCallsNames", with a negative lookahead in the regexp to ignore all hooks except "useSubscription": `/^(?!.*useSubscription).*$/`; That will disable checking the hook calls of all other hooks.

**Comment by oberruti** [comment]
> I appreciate the effort!🚀
> 
> As for validating only specific properties, it isn't possible currently. But I have plans for v3 where I'll bring greater flexibility and filtering capabilities. About only running for a specific hook/file, you could add a override in your eslint config, leaving `checkHookReturnObject` false as the default value, and as true for your useSubscription eslint override.
> 
> There's a difference between ignores, checks inside hooks are done on return statements, the "hook calls" wording mean checks that are ran against usages of the hook, e.g., in `const x = useSomething({y})` it'd verify if `y` is a primitive or memorized, so that's where `ignoredHookCallsNames` acts. For checking memo rules **inside** hooks there's only the option to enable/disable it entirely, hence my suggestion about using eslint overrides.
> 
> By the way, for hook calls in your case you could use "ignoredHookCallsNames", with a negative lookahead in the regexp to ignore all hooks except "useSubscription": `/^(?!.*useSubscription).*$/`; That will disable checking the hook calls of all other hooks.

Thank you so much for your answer!
I tried your suggestion as:

```
{
        strict: false,
        checkHookReturnObject: false,
        fix: { addImports: false },
        checkHookCalls: true,
        ignoredHookCallsNames: /^(?!.*useSubscription).*$/,
      },
```

but seems it's checking for everything instead of just `useSubscription`, am I doing something wrong?

**Comment by oberruti** [comment]
For example, there is overriding some const with `useCallbacks` and I just want to check inside `useSubscription` nothing else

**Comment by arthurgeron-work** [comment]
By the way it's a `Record` (e.g. Json), but forget what I said about ignoredHookCallsNames, the version using expressions wasn't released yet, my apologies.

**Comment by oberruti** [comment]
> By the way it's a `Record` (e.g. Json), but forget what I said about ignoredHookCallsNames, the version using expressions isn't released yet, my apologies.

That would be super useful for me and my team

**Comment by oberruti** [comment]
@arthurgeron @arthurgeron-work is there any chance to release that version using expressions?

**Comment by oberruti** [comment]
Hello @arthurgeron just catching up this to know if we could be able to implement the expressions soon, or we should go with another approach of other tech, thank you!

**Comment by arthurgeron-work** [comment]
> Hello @arthurgeron just catching up this to know if we could be able to implement the expressions soon, or we should go with another approach of other tech, thank you!

I'm looking into implementing support for expressions in a minor release this week. Though, as mentioned before, if your intention is only running that rule for a single hook or file, you can achieve that with ESLint's [overrides](https://eslint.org/docs/latest/use/configure/configuration-files#how-do-overrides-work). 
Also, plans for supporting individual prop name filtering are expected on the v3 release, but with no ETA.

**Comment by oberruti** [comment]
@arthurgeron that doesn't work for me because I need to check all the usages of the `hook`, i.e. everytime `useSubscription` is called, I need to check if the object sent with the config for the hook is wrapped with `useMemo`, so I will wait for the support on the expressions.

**Comment by arthurgeron-work** [comment]
By the way, is the eslint error/crash gone?

**Comment by oberruti** [comment]
Nope, just running it with fix: {addImports: false}

> quote_type
> Octavio Berruti
